condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
group_imports = "StdExternalCrate"
imports_indent = "Block"
fn_single_line = true
format_strings = true
match_arm_blocks = true
max_width = 80
reorder_imports = true
trailing_semicolon = true
use_field_init_shorthand = true
unstable_features = true
wrap_comments = true
