[workspace]
members = [
    "autocrypt",
    "buffered-reader",
    "ffi",
    "ffi-macros",
    "guide",
    "ipc",
    "net",
    "openpgp",
    "openpgp-ffi",
    "sq",
    "sqv",
    "store",
]

[profile.release]
debug = true
