[package]
name = "sequoia"
description = "A cool new OpenPGP implementation"
version = "0.8.0"
authors = [
    "Juga <juga@sequoia-pgp.org>",
    "Justus Winter <justus@sequoia-pgp.org>",
    "Kai Michaelis <kai@sequoia-pgp.org>",
    "Neal H. Walfield <neal@sequoia-pgp.org>",
]
documentation = "https://docs.sequoia-pgp.org/0.8.0/"
homepage = "https://sequoia-pgp.org/"
repository = "https://gitlab.com/sequoia-pgp/sequoia"
readme = "README.md"
keywords = ["cryptography", "openpgp", "pgp", "encryption", "signing"]
categories = ["cryptography", "authentication", "email"]
license = "GPL-3.0"

[badges]
gitlab = { repository = "sequoia-pgp/sequoia" }
maintenance = { status = "actively-developed" }

[workspace]

[dependencies]
buffered-reader = { path = "buffered-reader", version = "0.8" }
sequoia-rfc2822 = { path = "rfc2822", version = "0.8" }
sequoia-openpgp = { path = "openpgp", version = "0.8" }
sequoia-openpgp-ffi = { path = "openpgp-ffi", version = "0.8" }
sequoia-core = { path = "core", version = "0.8" }
sequoia-ffi = { path = "ffi", version = "0.8" }
sequoia-ffi-macros = { path = "ffi-macros", version = "0.8" }
sequoia-ipc = { path = "ipc", version = "0.8" }
sequoia-net = { path = "net", version = "0.8" }
sequoia-store = { path = "store", version = "0.8" }
sequoia-tool = { path = "tool", version = "0.8" }
sequoia-sqv = { path = "sqv", version = "0.8" }
sequoia-guide = { path = "guide", version = "0.8" }

[lib]
name = "sequoia"
path = "src/lib.rs"

[profile.release]
debug = true
