[package]
name = "sequoia"
version = "0.1.0"
authors = ["Neal H. Walfield <neal@gnu.org>"]

[workspace]

[dependencies]
buffered-reader = { path = "buffered-reader" }
openpgp = { path = "openpgp" }
sequoia-core = { path = "core" }
sequoia-ffi = { path = "ffi" }
sequoia-net = { path = "net" }
sequoia-store = { path = "store" }
sequoia-tool = { path = "tool" }

[lib]
name = "sequoia"
path = "src/lib.rs"
